### ISSUE TITLE
Support for RethinkDB 2.X

### ISSUE THREAD

**Issue by Tlvenn** [Workshape/reql-cli#2]
RethinkDB dependency should be upgraded to 2.x so that the CLI can connect to the latest version of RethinkDB.

**Comment by GordyD** [comment]
Thank you for the reminder! We'll get on it shortly.

**Comment by GordyD** [comment]
All dependencies have been updated. Specifically, RethinkDB has been bumped to 2.1.1.

**Comment by Tlvenn** [comment]
Great thanks!
